### PR TITLE
Using right PHP Syntax

### PR DESCRIPTION
**Pull request by Sulfatezzz**

### CODE REVIEW

**Comment by iksaku** [comment]
Thanks!

**Comment by PEMapModder** [comment]
:joy:

**Comment by iJoshuaHD** [comment]
u could just did from " . $variable . " to just $variable ...

**Comment by DinoKill** [comment]
I wish PHP could concatenate strings with the + operator. That's how it works in most other languages.

**Comment by PEMapModder** [comment]
What happens with PHP if you do `"\x01" + "\x02"`?

**Comment by caingaroo** [comment]
Is this like a hunger games plugin cause I have a hunger games plugin in phat form and pocket mine accept it on my server why is this I thought pocket mine servers wouldn't take phat form plugins

**Comment by iksaku** [comment]
@caingaroo You said nothing... Anyways, yes this is a _Hunger Games_ kinda plugin, but isn't finished yet...

**Comment by caingaroo** [comment]
Win will it been done?

**Comment by iksaku** [comment]
We don't have any ETA :/ sorry

**Comment by caingaroo** [comment]
Eta?
what this

**Comment by iksaku** [comment]
_ETA_ means ***Estimated Time of Arrival***, that is almost the same as _Time of Release_

**Comment by caingaroo** [comment]
What about a costume login like lbsg were there don't have to register but people who won't to protect there account can?

**Comment by iksaku** [comment]
Sorry, this isn't a support nor forum page, please refer to #LegendsOfMCPE on IRC to talk about it.

**Comment by caingaroo** [comment]
This was a suggestion for this plugin >.<

**Pull request merged**
