### PR TITLE
You shouldn't really miss this

### PR DESCRIPTION
**Pull request by Georggi**

### CODE REVIEW

**Comment by Falkirks** [comment]
:stuck_out_tongue_winking_eye:

**Comment by DinoKill** [comment]
I blame Eclipse!

**Comment by andrethegamer** [comment]
Dino please send me a .Phar file of the Hg Plugin please man you the best plugin maker please do it my email is andreleon911@gmail.com PLEASE MAN

**Comment by KyleTheHack3r** [comment]
@andrethegamer You can use PEMapModder's online conversion tool.

**Comment by andrethegamer** [comment]
Ok Thanks And Also What The Command For The Plugin Like What /hg didnt work

**Comment by andrethegamer** [comment]
KyleTheHack3r  What The Commands For Ingame To Join Arenas and make areana please list all thank you

**Comment by Georggi** [comment]
@andrethegamer This plugin is not done yet, it isn't working right now

**Pull request merged**
